---
- name: Install Nginx on web servers
  hosts: localhost
  gather_facts: no  # Avoid privilege escalation during fact gathering
  tasks:
    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present

